//Los Productos Los sirve el back-end por los precios y los tiempos
export default [
    {id:1,
    nombre: "Tubo Corto de Leche",
    type: "Diafragma",
    time: 1,
    precio: 5000,
    descripcion: "El plástico es un material ampliamente utilizado en envases y productos diversos. Es importante " +
    "reciclarlo para reducir su impacto ambiental.",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-45.jpg',
    items: 1
    },
    {id:2,
    nombre: "Valvula Colector",
    type: "Ordeños - Caucho",
    time: 1,
    precio: 2000,
    descripcion: "El Caucho",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-44.jpg',
    items: 1
    },
    {id:3,
    nombre: "Diafragma Pulsador",
    type: "Ordeños - Caucho",
    time: 1,
    precio: 2000,
    descripcion: "El Caucho Varios",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-43.jpg',
    items: 1
    },
    {id:4,
    nombre: "Empaque ",
    type: "Ordeños - Caucho",
    time: 1,
    precio: 2000,
    descripcion: "El Caucho Varios",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-42.jpg',
    items: 1
    },
    {id:5,
    nombre: "Bayoneta",
    type: "Ordeños - Caucho",
    time: 1,
    precio: 13300,
    descripcion: "El Caucho Varios",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-41.jpg',
    items: 1
    },
    {id:6,
    nombre: "Distribuidor de Vacio Yeter",
    type: "Ordeños - Caucho",
    time: 1,
    precio: 14100,
    descripcion: "El Caucho Varios",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-40.jpg',
    items: 1
    },
    {id:7,
    nombre: 'Flapper 1" 1/2',
    type: "Ordeños - Caucho",
    time: 1,
    precio: 19900,
    descripcion: "El Caucho Varios",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-39.jpg',
    items: 1
    },
    {id:8,
    nombre: "Copa Yeter",
    type: "Ordeños - Caucho",
    time: 1,
    precio: 24100,
    descripcion: "El Caucho Varios",
    img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-32.jpg',
    items: 1
    },
    {id:9,
        nombre: "Junta Cantina 40L",
        type: "Ordeños - Caucho",
        time: 1,
        precio: 39800,
        descripcion: "El Caucho Varios",
        img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-33.jpg',
        items: 1
    },
    {id:10,
        nombre: "Cauchos Varios",
        type: "Ordeños - Caucho",
        time: 1,
        precio: 2000,
        descripcion: "El Caucho Varios",
        img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-34.jpg',
        items: 1
    },
    {id:11,
        nombre: "Tapon Artificial Pezonera",
        type: "Ordeños - Caucho",
        time: 1,
        precio: 15100,
        descripcion: "El Caucho Varios",
        img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-35.jpg',
        items: 1
    },
    {id:12,
        nombre: "Cauchos Varios",
        type: "Ordeños - Caucho",
        time: 1,
        precio: 2000,
        descripcion: "El Caucho Varios",
        img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-36.jpg',
        items: 1
    },
    {id:13,
        nombre: "Diafragma",
        type: "Ordeños - Caucho",
        time: 1,
        precio: 2000,
        descripcion: "El Caucho Varios",
        img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-37.jpg',
        items: 1
    },
    {id:14,
        nombre: "Cauchos Varios",
        type: "Ordeños - Caucho",
        time: 1,
        precio: 2000,
        descripcion: "El Caucho Varios",
        img: 'http://cauchosmc.com/wp-content/uploads/2019/09/FOTOS-CM-38.jpg',
        items: 1
    },

];